---
name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    name: Linting Code Base
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install yamllint
          sudo apt-get update
          sudo apt-get -y install markdownlint

      - name: Lint with yamllint
        run: |
          yamllint . --format github

      - name: Lint with markdownlint
        run: |
          markdownlint `git ls-files *md`
