---
name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pymarkdownlnt yamllint

      - name: Lint with yamllint
        run: |
          yamllint . --format github

      - name: Lint with pymarkdownlint
        run: |
          pymarkdownlnt -d MD013,MD041 scan `git ls-files '*.md' ':!:*TEMPLATE/*md'`
